import {Platform, StyleSheet} from 'react-native';
import {block} from 'react-native-reanimated';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    backgroundColor: 'rgba(9,24,43,1)',
    flexDirection: 'row',
    paddingVertical: '5%',
    paddingHorizontal: '5%',
    alignItems: 'center',
  },
  headerIconStyle: {
    height: 30,
    width: 30,
    alignSelf: 'center',
  },
  headerTextStyle: {
    color: 'white',
    fontSize: 22,
    marginHorizontal: 70,
  },
  righticon: {
    flexDirection: 'row',
    marginLeft: 30,
  },
  unlock: {
    color: 'grey',
    padding: 12,
    fontSize: 25,
    marginLeft: 25,
  },
  header: {
    flex: 1,
    backgroundColor: 'rgba(9,24,43,1)',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  footer: {
    flex: 6,
    backgroundColor: 'rgba(9,24,43,1)',
  },
  logo: {
    top: 70,
    marginLeft: 30,
  },
  choose: {
    color: 'white',
    fontSize: 35,
    top: 0,
    marginLeft: 30,
  },
  chooses: {
    color: 'white',
    fontSize: 16,
    bottom: 20,
    marginLeft: 30,
  },
  text_footerimg: {
    color: 'grey',
    fontSize: 20,
    marginLeft: 25,
    marginTop: 10,
  },
  text_footer: {
    color: 'grey',
    fontSize: 20,
    marginLeft: 25,
    padding: 10,
    width: '100%',
  },
  text_footer1: {
    color: 'grey',
    fontSize: 20,
    marginLeft: 18,
    fontWeight: 'bold',
  },
  text_footernew: {
    color: 'grey',
    fontSize: 20,
    marginLeft: 18,
    bottom: 30,
    fontWeight: 'bold',
  },
  text_money: {
    fontSize: 30,
    color: 'grey',
    fontWeight: 'normal',
    padding: 15,
    marginLeft: 10,
  },
  text_moneyup: {
    textAlign: 'right',
    fontSize: 30,
    marginRight: 50,
    bottom: 20,
    color: 'grey',
    fontWeight: 'bold',
  },
  ref: {
    fontSize: 20,
    marginLeft: 235,
    bottom: 15,
  },
  detail: {
    height: '10%',
    marginLeft: 20,
    marginRight: 20,
  },
  seperate: {
    flexDirection: 'row',
    height: '18%',
    marginLeft: 20,
    marginRight: 20,
  },
  detail1: {
    height: '100%',
    justifyContent: 'center',
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 35,
    backgroundColor: '#fff',
  },
  detail12: {
    height: '130%',
    justifyContent: 'center',
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 35,
    backgroundColor: '#fff',
  },
  textinput: {
    flex: 1,
    marginRight: Platform.OS == 'ios' ? 0 : -12,
    paddingLeft: 20,
    color: '#000',
    fontSize: 20,
    backgroundColor: '#fff',
    height: 50,
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
  },
  textsep: {
    flex: 1,
    marginRight: Platform.OS == 'ios' ? 0 : -12,
    paddingLeft: 30,
    color: '#000',
    fontSize: 20,
    backgroundColor: '#fff',
    height: 50,
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
    width: '100%',
  },
  cont: {
    color: 'white',
    padding: 15,
    marginLeft: 20,
  },
  premium: {
    width: '40%',
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 70,
    marginLeft: 160,
    bottom: 45,
  },
  signIn: {
    width: '50%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 70,
    marginLeft: 50,
  },
  pay: {
    padding: 20,
    marginLeft: 30,
  },
  share: {
    width: '35%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 70,
    marginLeft: 220,
    bottom: 82,
  },
  Login: {
    bottom: -45,
  },
  socialIcon: {
    height: 30,
    marginRight: 290,
    top: 10,
  },
  textSign: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  Create: {
    color: '#f2f2f2',
    fontSize: 18,
    top: 15,
    marginLeft: 30,
  },
  Create1: {
    color: '#f2f2f2',
    fontSize: 18,
    bottom: 5,
    marginLeft: 210,
  },
});

export default styles;
